version: '3.8'

services:
  mysql:
    image: mysql:8.3.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment :
      - MYSQL_ROOT_PASSWORD=666llx666
      - MYSOL_LOWER_CASE_TABLE_NAMES=0
    ports:
      - "8080:8080"
    volumes :
      - ./data/mysql:/var/lib/mysql